name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-webpages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install enchant
      run: sudo apt-get install -y libenchant-2-2

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade -r python-requirements.txt

    - name: Build HTML
      run: make html

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v2
      with:
        name: html-docs
        path: _build/html

  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libenchant-2-2 latexmk texlive-xetex texlive-fonts-recommended texlive-latex-recommended
        sudo apt-get install -y texlive-luatex
        pip install --upgrade pip
        pip install --upgrade -r python-requirements.txt

    - name: Build PDF
      run: make latexpdf

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf-docs
        path: _build/latex/*.pdf

  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y hunspell-en-us nuspell libenchant-2-2 python3-pip python3-venv python3-wheel python3-cairo make git
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install --upgrade -r python-requirements.txt

    - name: Run spellcheck
      run: |
        source venv/bin/activate
        SPHINXOPTS='-j auto -W' make spelling

  deploy-webpages:
    runs-on: ubuntu-latest
    needs: build-webpages
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download HTML artifact
      uses: actions/download-artifact@v2
      with:
        name: html-docs
        path: _build/html

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh $GITHUB_ACTOR@joan.th-deg.de -- rm -rf public_html/$GITHUB_REPOSITORY
        scp -r _build/html $GITHUB_ACTOR@joan.th-deg.de:public_html/$GITHUB_REPOSITORY
